### ISSUE TITLE
Issues with connection disposal

### ISSUE THREAD

**Issue by carl-berg** [mattiasnordqvist/Galactic-Waste-Management#45]
A few times we've run into an issue where GWM fails to migrate up in azure:
```csharp
2019-11-20T09:49:49.1020681Z [38;2;255;0;0m [0m[38;2;255;36;0m#[0m[38;2;255;72;0m#[0m[38;2;255;109;0m#[0m[38;2;255;145;0m#[0m[38;2;255;182;0m [0m[38;2;255;218;0mG[0m[38;2;255;255;0mA[0m[38;2;218;255;0mL[0m[38;2;182;255;0mA[0m[38;2;145;255;0mC[0m[38;2;109;255;0mT[0m[38;2;72;255;0mI[0m[38;2;36;255;0mC[0m[38;2;0;255;0m [0m[38;2;0;255;36mW[0m[38;2;0;255;72mA[0m[38;2;0;255;109mS[0m[38;2;0;255;145mT[0m[38;2;0;255;182mE[0m[38;2;0;255;218m [0m[38;2;0;255;255mM[0m[38;2;0;218;255mA[0m[38;2;0;182;255mN[0m[38;2;0;145;255mA[0m[38;2;0;109;255mG[0m[38;2;0;72;255mE[0m[38;2;0;36;255mR[0m[38;2;0;0;255m [0m[38;2;36;0;255mE[0m[38;2;72;0;255mN[0m[38;2;109;0;255mG[0m[38;2;145;0;255mA[0m[38;2;182;0;255mG[0m[38;2;218;0;255mE[0m[38;2;255;0;255mD[0m[38;2;255;0;218m [0m[38;2;255;0;182m#[0m[38;2;255;0;145m#[0m[38;2;255;0;109m#[0m[38;2;255;0;72m#[0m[38;2;255;0;36m [0m
2019-11-20T09:49:49.1028816Z [38;2;255;255;255mManaging galactic waste in [0m[38;2;255;165;0mMyDB[0m
2019-11-20T09:49:49.1034888Z [38;2;255;255;255mRunning LiveField mode[0m
2019-11-20T09:49:51.2208092Z [38;2;105;105;105mFound changed or added RunIfChanged-scripts.[0m
2019-11-20T09:49:51.2414726Z [38;2;105;105;105mExecuting script '[0m[38;2;255;255;224mMyNamespace.Scripts.RunIfChanged.CreateSynchronizeInvoiceRowView.sql[0m[38;2;105;105;105m'[0m
2019-11-20T09:49:52.7427982Z [38;2;255;0;0mThis SqlTransaction has completed; it is no longer usable.[0m

Unhandled Exception:
System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
   at System.Data.SqlClient.SqlTransaction.ZombieCheck()
   at System.Data.SqlClient.SqlTransaction.Commit()
   at JellyDust.Transaction.Commit()
   at GalacticWasteManagement.TransactionManager.Dispose()
   at GalacticWasteManagement.MigrationBase.ManageGalacticWaste()
   at GalacticWasteManagement.GalacticWasteManager.Update(Func`2 migratorFactory, Dictionary`2 parameters, Dictionary`2 scriptVariables)
   at GalacticWasteManagement.GalacticWasteManager.Update(String mode, Dictionary`2 parameters, Dictionary`2 scriptVariables)
   at Envirotainer.Portal.Financials.Migration.Runner.Program.<Main>(String[] args)
PowerShell exited with code '1'.
```
also when digging into this i found that `TransactionManager.singleTransaction` gets initialized with `Parameters.Optional(new InputBool("transaction-per-script", ""), false)` which seems seem wrong? I don't know if it's related at all but maybe something that can be looked into.

**Comment by carl-berg** [comment]
Seems like the issue might have been an issue with the sql inside the script but this was the resulting error which could be confusing

**Comment by mattiasnordqvist** [comment]
What do you think is wrong with `transactionManager.singleTransaction` getting initialized with `Parameters.Optional(new InputBool("transaction-per-script", ""), false)`?

**Comment by mattiasnordqvist** [comment]
Ah now I see! 😅

**Comment by mattiasnordqvist** [comment]
looks ok? https://github.com/mattiasnordqvist/Galactic-Waste-Management/commit/ccd3802c156947d7564bb08da315cec9ee6e5c87 @carl-berg

**Comment by carl-berg** [comment]
Looks good!

Any idea on the other issue with `This SqlTransaction has completed; it is no longer usable.` exception when running bad sql?

**Comment by mattiasnordqvist** [comment]
I'll look into it someday!
